---
- hosts: all
  roles:
    - selinux
    - firewall
    - kernel
    - transparent_hugepage
    - limits
    - hostname
    - ipv6
    - ntp
    - dig
    - cdh_repos
    - oracle_jdk
    - postgresql_client
    - dns_client
